import { Kanit } from "next/font/google";
import "./globals.css";
// import Header from "@/components/Header";
import Footer from "@/components/Footer";

const kanit = Kanit({ weight:'500', subsets: ["thai"],
  weight:['500'], 
  display:"swap"
});

export const metadata = {
  title: "Supreme Infrastructure",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        {/* <Header/> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
